### ISSUE TITLE
Decide on smart contracts and channels upgradability pattern.

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#22]

**Comment by hackaugusto** [comment]
> but I was thinking of an alternative implementation, without the need to version the internal Raiden client logic:

If there are two nodes running, one for each network, mediation doesn't work, because you need to have the payer and payee channel states in the same node. This effectively means the networks will be disjoint, and making a transfer go through multiple networks won't work.

You could argue that not all nodes need to be on both networks at the same time, which is valid. But if we want to have some, we need to have the code in place anyways, so I would prefer to have a single code base which supports both, and then let the user decide if he wants or not to be connected on different versions of the network.

**Comment by loredanacirstea** [comment]
> because you need to have the payer and payee channel states in the same node. This effectively means the networks will be disjoint, and making a transfer go through multiple networks won't work.

In a way, I was proposing to keep them disjoint. 
 
E.g. `LockedTransfer` could describe the cross-network hops: `network_hops = [{ network_version: 'xx', initiator: 'address', target: 'address'}]` (just an example), where the `target` address from one cross network mediated transfer must be the same as the `initiator` for the next network mediated transfer.
And between `C1` and `C2` you would not have a channel (on-chain or off-chain), though you still need to keep some payer/payee state regarding the messages. You would only exchange basic signed messages to make `C2` trigger a `LockedTransfer` in the next network or receive a `SecretReveal` in `C1` and make sure to forward it to `B1`. 
Not sure if this would actually work, as I have not thought it out fully.

**Comment by karlb** [comment]
We will deploy separate smart contracts and use mediators to do payments between the old and new contracts.
