### ISSUE TITLE
Assess whether we can support withdrawing tokens without closing the channel.

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#26]

**Comment by hackaugusto** [comment]
I thought about this a bit, there are two things that we need to consider:

- Withdraw must first update the available balances off-chain, to avoid double spend.
- The balance proof must be updated to allow for deposits and withdraws

### Off-chain withdraw

- The `withdrawer` sends a `RequestWithdraw` to the counterparty.
  - This message will have the fields `withdraw_amount` and `channel_id`.
- The counterparty validates the `RequestWithdraw`, making sure that the `withdrawer` request amount is less than *available_balance*.
- If the request is valid, the counterparty deducts the `RequestWithdraw.withdraw_amount` from the `withdrawer.available_balance` and sends back a signed `Withdraw` message (this message too, will contain the `withdraw_amount`, `channel_id`, and an additional field for the `counterparty_signature`)
  - At this point, the total_cacity of the off-chain channel is reduced
- When the withdrawer wants, it can sign the `Withdraw` message and send it on chain.

The above protocol is sufficient to prove on-chain that `withdrawer` had at least the balance available to withdraw, and to avoid double spend since the counterparty must authorize it first.

**Comment by hackaugusto** [comment]
Okay, I think I got a working proposal:

- The on-chain Participant data structure must be changed:
  - The field `deposit` must become strictly monotonic.
  - A field `total_withdraw` must be added, this too will be strictly monotonic.
- A field `deposit` must be added to the channel, this is **not** monotonic.

A particpant **off-chain** available balance will become (used to validate transfers):

```
participant_on_chain.total_deposit
- participant_off_chain.withdraw
- participant_off_chain.locked_amount
- participant_balance_proof.transferred_amount
+ counterparty_balance_proof.transferred_amount
```

`participant_off_chain.withdraw` will be smaller than the on-chain counterpart until the withdraw is actually done on-chain, that is to avoid double spend problems as explained in the previous comment.

The non-closer **on-chain** net balance will become (used in settled):

```
non_closer_balance = counterparty_balance_proof.transferred_amount
- participant_balance_proof.transferred_amount
- participant.monotonic_withdraw
+ participant.monotonic_deposit
```

The balance will be bound against the channel deposit, and not the participant total balance:

```
non_closer_balance = min(max(non_closer_balance, 0), channel.deposit)
```

And the *closer* on-chain balance will be the rest of  the channel deposit:

```
closer_balance = channel.deposit - non_closer_balance
```

withdraw is only allowed if the channel is not closed and it will preserve the monotonicity of the `withdraw` field, we don't need to add the withdraw amount in the balance proof (otherwise it would be annoying to synch the nodes).

As before, the node that fails to provide the balance proof, may lose part of its balance.

**Comment by LefterisJP** [comment]
> The field deposit must become strictly monotonic.

Isn't this already the case?

As a proposal it sounds correct and should achieve the required result.

So essentially do the changes that you proposed above to the smart contract data structure and off-chain channel data structures.

Then also add two new message types. The `RequestWithdraw` and the `Withdraw` message.

Some Questions:

1. With the current proposal we make it a unanimous withdraw. Essentially a participant won't be able to withdraw funds from a channel, without closing it unless his counterparty agrees. That is fine I suppose. But we should document it.

2. If the non-withdrawer closes the channel when he receives the RequestWithdraw, there is no harm done since the Withdraw needs to be signed by the withdrawer **after** it has been signed and sent back by the counterparty to be valid. Right?

3. Could we make some modification to allow both parties the option to withdraw funds at the same time? The messages for Alice and Bob could go like this:

    - Alice sends a `RequestWithdraw` for X tokens to the counterparty
    - Bob verifies balance and:
        a. Either signs it and sends it back to the Alice who can submit it on chain.
        b. Or adds a request for Y tokens withdrawal signs it and sends it back to the Withdrawer.
    - If (a) we are done. If (b) then Alice needs to also verify balance for Bob, sign it again and then send if back to the him. Note that here Alice would not have the option to submit it on-chain before signing because the message would contain an unverified balance sent by Bob. This would have to be enforced by the contract.
    - Finally Bob would get the message, sign it one more time and then submit it on chain.

**Comment by hackaugusto** [comment]
> Isn't this already the case?

Yes, but withdraw is not supported ATM, the property must hold after withdraw is added.

> If the non-withdrawer closes the channel when he receives the RequestWithdraw, there is no harm done since the Withdraw needs to be signed by the withdrawer after it has been signed and sent back by the counterparty to be valid. Right?

Withdraw is forbid for closed channels, even if the message `withdraw` was sent back it couldn't be used.

> Could we make some modification to allow both parties the option to withdraw funds at the same time? The messages for Alice and Bob could go like this:

This only makes sense if there is extra coordination for the nodes, what is the benefit for this, saving one transaction?

I would simply have each node do their own round of withdraws.

**Comment by LefterisJP** [comment]
> This only makes sense if there is extra coordination for the nodes, what is the benefit for this, saving one transaction?

Yes it's to save one on-chain transaction. Keep in mind our goal is to minimize on-chain transactions at all cost.

**Comment by loredanacirstea** [comment]
Proposal:

(wip)


- `deposit`, `withdrawn_amount`, `transferred_amount` - monotonically increasing
- `participant` decides what amount he withdraws based on available funds (balance proofs + locked transfers that can be unlocked); he does not need an approval from his `partner` on the amount, as long as this amount is available to him
- both participants need to be online in order to exchange messages
- add `withdraw_window` - time in which the withdraw can be made on-chain
- add `block_stamp` for the withdraw balance proof from the partner that the participant will use to prove received tokens. This along with `withdraw_window` will make sure that the `withdraw` process has finality, so that the off-chain channel can resume activity (either after receiving an `ChannelWithdraw` event or `withdraw_window` has passed)
- after `partner` signed the block stamped proof, any channel transfers that lower the `participant`'s available balance are stopped for the `withdraw_window` duration.


**Balance proof logic**

- balance proof from partner - no problem if it is older, the `participant` is the one that cannot withdraw more tokens.
- block stamped balance proof from `participant` - needs to be **the last available balance proof**; this is why we need the block stamp & channel activity disabling

**To be determined**
- due to Solidity's `stack too deep` error (max 16 local variables), the `TokenNetwork.withdraw` will need to be refactored (e.g. arrays or using `struct` from ABIv2 could solve it).
- above optimizations of signing withdrawn amounts from @hackaugusto should be considered instead of providing whole proofs; though I was going for reusing similar protocols for simplicity & security (doing the calculations on-chain based on the same type of balance proofs felt more secure, but I would have to think this through)
- `withdraw_timeout` - set at channel creation / global variable, modifiable? - chain congestion issues (you can just wait; imo, channels are not meant for easy in-out to make token trading easy).
- maybe additional checks for `participant_available_balance`
- make sure `locked_amount` logic from batch unlock is correct


# TokenNetwork contract


- using the latest proposals for balance proof: https://github.com/raiden-network/spec/issues/25#issuecomment-375467874
- using the new batch unlock ideas: https://github.com/raiden-network/spec/issues/35#issuecomment-375480433, https://github.com/raiden-network/spec/issues/35#issuecomment-375487867, https://github.com/raiden-network/spec/issues/35#issuecomment-375510947, https://github.com/raiden-network/spec/issues/35#issuecomment-375511910


```

event ChannelWithdraw(uint256 channel_identifier, address participant, uint256 withdraw_amount);

function withdraw(
    uint256 withdraw_amount,
    uint256 channel_identifier,
    uint64 nonce_partner,
    uint256 transferred_amount_partner,
    bytes32 locksroot_partner,
    bytes32 additional_hash_partner,
    bytes merkle_tree_partner,
    bytes partner_signature,
    bytes participant_withdraw_signature,  // possibly needed for withdrawDelegate

    uint64 nonce_participant,
    uint256 transferred_amount_participant,
    bytes32 locksroot_participant,
    bytes32 additional_hash_participant,
    bytes merkle_tree_participant,
    uint256 block_stamp,
    bytes participant_signature,
    bytes partner_withdraw_signature,
    )
    external
{
    require(block_stamp + withdraw_window >= block.number);

    address partner = recoverAddressFromSignedProof(
        channel_identifier,
        nonce_partner,
        transferred_amount_partner,
        locksroot_partner,
        additional_hash_partner,
        merkle_tree_partner,
        partner_signature
    );

    address participant = recoverAddressFromSignedWithdrawProof(
        channel_identifier,
        nonce_participant,
        transferred_amount_participant,
        locksroot_participant,
        additional_hash_participant,
        merkle_tree_participant,
        block_stamp,
        participant_signature
    );

    address partner_withdraw_proof = recoverAddressFromSignedWithdrawProof(
        channel_identifier,
        nonce_participant,
        transferred_amount_participant,
        locksroot_participant,
        additional_hash_participant,
        merkle_tree_participant,
        block_stamp,
        partner_withdraw_signature
    );
    require(partner == partner_withdraw_proof);
    [...]

    locked_amount_participant = calculateAndVerifyLockedAmount(merkle_tree_partner);
    locked_amount_partner = calculateAndVerifyLockedAmount(merkle_tree_participant);

    total_deposit = participant1_state.deposit + participant2_state.deposit - participant1_state.withdrawn - participant2_state.withdrawn


    participant_available_balance = (
        participant_state.deposit
        - participant_state.withdrawn
        - transferred_amount_participant
        + locked_amount_participant
        + transferred_amount_partner
        - locked_amount_partner
    );
    require(participant_available_balance >= withdraw_amount)

    participant_state.withdrawn += withdraw_amount
    // Do the transfer

    // Emit ChannelWithdraw event
}
```

**Comment by LefterisJP** [comment]
> add block_stamp for the withdraw balance proof from the partner that the participant will use to prove received tokens.

`block_stamp`? As in block timestamp? Or block number? What is a block stamp? From the code it looks like a block number of .. perhaps the beginning of the withdrawal? So is it the block number that the withdrawal started?

**Comment by loredanacirstea** [comment]
I updated my proposal. It is a block number.

**Comment by hackaugusto** [comment]
Spreadsheet with some test cases: https://docs.google.com/spreadsheets/d/1wAHQOp0L3ngnzyzodr_isskDCeJTAbQ8rDb_xredIig/edit?usp=sharing
