### ISSUE TITLE
MS - if node called update but it did not unlock all the locks

### ISSUE THREAD

**Issue by loredanacirstea** [raiden-network/spec#31]
The Monitoring Service might choose to only call `updateTransfer` and not call `unlock` for locks that have the secret revealed, therefore the participant can lose money.

How should we deal with this? 
- Punish MS directly in some way
- Implement a rating system for MSs and a whitelist / preferred services
- Batch transfer data to be unlocked and attach this to the balance proof, making the participant sign all of this data -> call a wrapper TokenNetwork function that would do `updateTransfer` + `unlock` for each lock.
  - As Augusto said, maybe some gas cost can be saved by calculating the `locksroot` on chain for all these locks, as opposed to calling `computeMerkleRoot` for each lock.
  - cons: we cannot limit the number of locked transfers, we cannot batch to many (out of gas)
  - related issue about batching in `unlock`:  https://github.com/raiden-network/spec/issues/35

**Comment by loredanacirstea** [comment]
(proposal after a discussion with @hackaugusto and @konradkonrad ; please correct me if anything is off)

- new logic for `settleChannel` & `unlock`
- also see https://github.com/raiden-network/spec/issues/25#issuecomment-375467874 for MS behavior + `updateTransfer` partial specs - MS ONLY needs to call `updateTransfer`, it does not need to `unlock` locks.

## Settling the channel

! `locked_amount` needs to be included in the balance proof and signed = total amount of tokens locked inside transfers, that is not included in the `transferred_amount`

A -> TokenNetwork: `closeChannel`
MS/B -> TokenNetwork: `updateTransfer` (can be called multiple times)
A/B -> TokenNetwork: `settleChannel` (transfers everything except `locked_amount`)
A -> TokenNetwork: `unlock` (anytime after settle; until then, tokens remain in contract)
B -> TokenNetwork: `unlock` (anytime after settle; until then, tokens remain in contract)

**PROs**:
- called after settle, we know the state of the locks - expired / secret revealed etc.
- `unlock` is a batch unlock - 1 transaction for all locked transfers - see: https://github.com/raiden-network/spec/issues/35
- participants can unlock at any time - maybe doesn't make sense to unlock if gas cost is bigger than token value - this can change at some point in time
- MS doesn't need to call `unlock`

**Notes**
- we may want to allow `unlock` when someone does a `withdraw` transaction (specs should be incoming) - so in the same transaction. for a withdraw, the off-chain channel should be put in standby so it does not SEND any more tokens; more at: https://github.com/raiden-network/spec/issues/26

## SecretRegistry contract

```
    // lockhash => block number at which the secret was revealed
    mapping(bytes32 => uint256) public lockhash_to_block;

    /*
     *  Events
     */

    event SecretRevealed(bytes32 indexed lockhash);

    function registerSecret(bytes32 secret) public returns (bool) {
        bytes32 lockhash = keccak256(secret);
        if (secret_to_block[lockhash] > 0) {
            return false;
        }
        secret_to_block[lockhash] = block.number;
        SecretRevealed(lockhash); // check if we need SecretRevealed(lockhash, secret);
        return true;
    }

```

**PROs**
- each node listens to the indexed `hashlock` - no need to store secrets off-chain unless querying the blockchain is too slow -> once the `secret` is registered -> any node knows and can unlock.

## Some context

### Good Behavior - OFF chain

<img width="968" alt="screen shot 2018-03-22 at 10 01 50 pm" src="https://user-images.githubusercontent.com/4785356/37800599-b2d15f54-2e23-11e8-899e-cad7e06c8094.png">

### Bad Behaviour - M2 does not send the BP to Target

<img width="1572" alt="screen shot 2018-03-22 at 10 02 06 pm" src="https://user-images.githubusercontent.com/4785356/37800623-c6e6b6d8-2e23-11e8-9a13-8f9a9dec2715.png">

**Notes:**
- CHOICE: if gas cost for `rergisterSecret` > transfer `amount` => node can choose to lose the tokens
- maybe split the gas cost of registering the secret on chain by requesting an HTL transfer from the other nodes with the same secret & smaller timeout. (Konrad's proposal)

**PROs**:
- don't need to `closeChannel` & `unlock` -> save gas cost
- we only have 1 ON chain transaction to do
- channel can be closed normally -> close channel OFF chain -> do not receive any more off chain transfers -> wait until all locks expire / are revealed -> `closeChannel` ON chain with maximum `transferred_amount` possible
- don't need to storage for unlocked locks ON chain (`TokenNetwork`)

### Bad Behaviour - M2 does not send the SecretReveal to M1

<img width="1294" alt="screen shot 2018-03-22 at 10 02 53 pm" src="https://user-images.githubusercontent.com/4785356/37800640-d64897d6-2e23-11e8-87b1-8107d78ba5dc.png">

??? = 
- add additional message - to convince someone to registerSecret ON chain?

**Comment by hackaugusto** [comment]
> we may want to allow unlock when someone does a withdraw transaction (specs should be incoming) - so in the same transaction. for a withdraw, the off-chain channel should be put in standby so it does not SEND any more tokens; more at:

I didn't understand this, could you clarify?

> Secret can be used by all nodes to unlock the transfer after settling the channels

It's also possible to unlock off-chain, as long as we have the proper messages and the nodes are cooperating.

> don't need to closeChannel & unlock -> save gas cost

Additionally the channel doesn't need to be closed, which may be good if it's just an intermittent behavior

> don't need to storage for unlocked locks ON chain (TokenNetwork)

This will depend on how the batch unlock is implemented, we may still have the mapping to inform if the lock was already withdrawn

> CHOICE lose the transfer or registerSecret

This is not a viable choice. The mediator may be an attacker that just doesn't want to send a balance proof back, but it is online and will unlock the lock the from previous hop. The target must register the secret on-chain if it has revealed the secret off-chain, even though it did not receive a balance proof.

> maybe split the gas cost of registering the secret on chain by requesting an HTL transfer from the other nodes with the same secret & smaller timeout. (Konrad's proposal)

I don't like this idea. It requires all nodes from the path to be known and requires additional coordination (keep in mind that at least one of these nodes is already unresponsive).

> ??? =

The mediator must register the secret on-chain, because it has payed to the next hop already (otherwise these tokens are lost)

> add additional message - to convince someone to registerSecret ON chain?

nope, the blockchain is enough, and I believe the reveal secret is good enough (we could have a message that is more explicit and it includes the block height in which the secret was registered, haven't thought about it much though)

**Comment by loredanacirstea** [comment]
> nope, the blockchain is enough, and I believe the reveal secret is good enough (we could have a message that is more explicit and it includes the block height in which the secret was registered, haven't thought about it much though)

At that point in time, no one registered the secret on chain

**Comment by hackaugusto** [comment]
> At that point in time, no one registered the secret on chain

Ah, sorry, I misread. Still though, either the node is required to register the secret to not lose token, or it doesn't have a reason to go on-chain and should not send a transaction.

**Comment by LefterisJP** [comment]
General comment:

The proposal as it's written with PROs and Notes sections at first sight looked like two different proposals while they are all part of the same proposal. At first sight I thought it's somehow either (1) change in the settle protocol or (2) a secret registry contract. Reformat/reword it a bit to make this clear.

> we may want to allow unlock when someone does a withdraw transaction (specs should be incoming

Let's keep withdraw out for now. Let's focus on the simplest form of the protocol for the first MVP version. Withdraw does not belong there yet.

> I didn't understand this, could you clarify?

@hackaugusto Loredana is referring to the cooperative withdraw from a channel without closing it [link](https://github.com/raiden-network/spec/issues/26)

> CHOICE: if gas cost for registerSecret > transfer amount => node can choose to lose the tokens
> This is not a viable choice. The mediator may be an attacker that just doesn't want to send a balance proof back, but it is online and will unlock the lock with the previous hop. The target must register the secret on-chain if it has revealed the secret off-chain if it did not receive a balance proof.

@hackaugusto Yeah but in the given example if M2 sends token whole value is less than the gas cost for the on-chain transfer of secret registering can't he just choose to not go on-chain for that particular transfer and just lose token from that particular HTL? 

The question I guess here @loredanacirstea would be and then what happens? You would be in a channel with a misbehaving node and would need to close/settle anyway since your partner has broken protocol and will most probably do it again in the future. So you would need to terminate that channel to protect your funds.

> maybe split the gas cost of registering the secret on chain by requesting an HTL transfer from the other nodes with the same secret & smaller timeout. 

I would try to avoid that. Sounds like too many moving parts and quite a complication to the protocol.

> ??? =

If M2 does not reveal the secret to M1 then M2 does not get paid by M1. It's in his best interest to do so.

**Comment by loredanacirstea** [comment]
case ???:

> The mediator must register the secret on-chain, because it has payed to the next hop already (otherwise these tokens are lost)


> If M2 does not reveal the secret to M1 then M2 does not get paid by M1. It's in his best interest to do so.

M2 has the secret. It can `unlock` the tokens. 
M1 does not have the secret. It cannot `unlock` and it cannot receive a balance proof from Initiator.

**Comment by LefterisJP** [comment]
> M2 has the secret. It can unlock the tokens.
> M1 does not have the secret. It cannot unlock and it cannot receive a balance proof from Initiator.

At least with the current protocol M2 would do that unlock on chain so M1 would also see the secret if this happened and be able to continue the protocol with the initiator.

Or is there something else I am missing?

**Comment by loredanacirstea** [comment]
> M2 would do that unlock on chain

why? M2 goes offline before passing on the secret to M1. even though he sends the BP to Target.
I may be missing something about the current implementation (e.g. sending BP to target & sending SecretReveal to M1 may be done in the same function or in the specific order: BP -> then SecretReveal => no issue).

But if M2 is a malicious Raiden client -> it may happen that the SecretReveal chain stops there.

**Comment by hackaugusto** [comment]
can we close this issue and rely on the batch unlock #35  ?

**Comment by LefterisJP** [comment]
@hackaugusto perhaps then @loredanacirstea can move her flow graphs and whatever else could be useful from here to there before closing.
