### ISSUE TITLE
Transport: message format

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/spec#49]
- Raiden Matrix Transport will use binary packing to have a prototype working without much refactoring (JSON will be used as step two once the Matrix layer is integrated & tested)
- MS & PFS will use JSON to encode the messages

TBD:
- [ ] decide if messages should use some sort of envelope
- [ ] decide how the data will be signed and if the signature will be part of JSON (we can use canonical JSON to encode the message into a string to sign)
- [ ] signatures should be `ecrecover` compatible

**Comment by hackaugusto** [comment]
> decide how the data will be signed and if the signature will be part of JSON (we can use canonical JSON to encode the message into a string to sign)
> signatures should be ecrecover compatible

For messages that are used by smart contracts, the signature must be computed on the keccak256 hash of `signed_values` encoded following the Etehreum Contract ABI. [example](https://github.com/raiden-network/spec/blob/9c2b4206a545ae4aa916706ba137ca76f78d4d63/messaging.rst#balance-proof).

If the message has additional data that is not revealed to the blockchain, then a hash of the data should be used and the hash needs to be included as part of the `signed_values` as the last value.

Because we have the above, I suggest that other messages follow a similar scheme.

**Comment by andrevmatos** [comment]
@hackaugusto this signature is only for source validation in the transport layer, they're never used anywhere outside it. Contract related messages are signed previously, and are in a field inside the message body. Therefore, I'd push for simply signing the hash of the message, possibly in a `eth_sign` compatible manner, and appending it to the message itself (with some kind of separator, maybe), no need to even encapsulate it in JSON, as body json encoding/decoding should be done after this signature validation.

**Comment by heikoheiko** [comment]
> Raiden Matrix Transport will use binary packing to have a prototype working without much refactoring

does that mean, the messages are actually binary and not in a JSON envelope? i would have thought, that the raiden messages are hexencoded and put in an envelope. and i suggest to add some code, which sniffs the binary message and translates some key-values (e.g. sender, receiver, message-type) to plain text and puts them in the envelope. using matrix is also supposed to help with debugging and having plain readable messages is very helpful here. 
unnecessary stuff can be removed later. when developing Ethereum we should have had a a more verbose protocol during development to ease debugging.

**Comment by ulope** [comment]
Please see https://github.com/raiden-network/spec/pull/38#issuecomment-378304265 for what we discussed during last weeks call.

> using matrix is also supposed to help with debugging and having plain readable messages is very helpful here.

Exactly. This is also why moving away from the binary message format will make life much easier (both because of readability and maintainability). But of course that doesn't has to happen immediately.

**Comment by ulope** [comment]
1. We're (or rather Andre) isn't doing that for now - however as far as we've discussed possible implementations it wouldn't be a change to have the core models understand json but rather to remove the tight coupling with the binary format we currently have and add serialisation at the boundary to the transport so the internal representation would be completely transport agnostic.
2. Right, but debugging would then really be the only use-case since those values will not be part of the signed message content and therefore can't be trusted

**Comment by heikoheiko** [comment]
2. yes. but debugging is an awesome use case ;)

**Comment by pcppcp** [comment]
> I guess what @hackaugusto  is asking: Why have the external signature at all. In the udp transport we also didn’t have it and anybody could send any message to any node
just to chip in: to prove identity of the sender. 
Signed hashes of BP or similar data used as parameters of SC methods on-chain will be send as they are now (probably as a hex encoded string). But I guess there's no harm in signing the metadata too - in order to prevent replay attacks and to allow further extensions of the protocol.
If I am not mistaken that's exactly what `SignedMessage::sign()` does now.

**Comment by andrevmatos** [comment]
As discussed above, the current implementation doesn't sign or validate a per-message signature. It's expected that messages containing signatures will be handled a little bit up the stack (e.g. balance proof signature will be checked on balance-proof event handler). Instead, we require a matrix user metadata (namely, user's displayName) to be it's eth_signed `userId`, and we ignore messages otherwise. Notice it doesn't couple our implementation with matrix, as this validation is done only inside transport, and this signature is done and checked outside the message bodies, is fully transparent to the core, and is only an additional transport check layer (to couple `userId` <-> `eth address`).
And the message encoding, in matrix, is JSON right now, but also transport agnostic, as the transport [de/en]code the messages. This way, we've easily debugable messages, signing of sensitive information done on code (avoiding signing twice), and transport per-client identity check which doesn't touch the messages itself.

**Comment by LefterisJP** [comment]
Closing this as it's finished for raiden core. Open other issues for PFS and MS.
