### ISSUE TITLE
what's the max number of unlocked locks?

### ISSUE THREAD

**Issue by nkbai** [raiden-network/spec#92]
there is a function unlock in the tokennetwokr.sol,
I test that if there are two locks, this call will be success, but if  there are three locks, the call will be failure.

Does that mean a raiden node must not accept more than two unlcked transfers at the same time?

**Comment by loredanacirstea** [comment]
Calling `unlock` with 6 locks works and currently costs `80566`.
Can you provide some code to reproduce the issue? The transaction might fail for a different reason.

Otherwise, you are correct: we will limit the number of pending transfers to the maximum of locks that we can safely provide to `unlock`.  The issue is: https://github.com/raiden-network/raiden/issues/439

We also have in mind some ways to unlock off-chain these locks with secrets revealed on-chain.
Issue: https://github.com/raiden-network/raiden/issues/1628

**Comment by nkbai** [comment]
thanks ,it's my problem,
7 locks, gas is 86372

**Comment by nkbai** [comment]
200 locks, length of merkle_tree_leaves is 19200 bytes, gas is 1541441
it seems that only limit is the gas limit of ethereum node.

**Comment by LefterisJP** [comment]
yep exactly @nkbai but we should choose a sensible value as the gas limit can and will also change as time goes by
